version: "3"

services:
  db:
    image: postgres:16.2-alpine
    container_name: student-accommodation-local-db
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: localadmin
      POSTGRES_DB: studentaccommodationlocaldb
    ports:
      - "5432:5432"

  student-accommodation-back-end:
    container_name: student-accommodation-back-end
    image: student-accommodation-back-end:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=studentaccommodationlocaldb
      - USER_DB=localadmin
      - PASSWORD_DB=admin
      - DB_URL=jdbc:postgresql://db:5432/studentaccommodationlocaldb
      - JWT_SECRET=jvc+QC/0myyJ9+//Rzo+qYxfMmHDiQdlysvcT9XhUF7/6mvHD9evZBB/ngNAMwTD6sDDQgf4vS0QDZ8JYLoBOA==
      - JWT_EXPIRATION=36000000

  minio:
    image: minio/minio
    container_name: student-accommodation-minio
    ports:
      - "9000:9000"  
      - "9001:9001"  
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
  
volumes:
  minio_data: